version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo-list
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: todo-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: todo-list
      SMTP_EMAIL: 21130291@st.hcmuaf.edu.vn
      SMTP_PASSWORD: Binhvui2003*
    command: ["./todo-app"]

volumes:
  mysql-data:
