// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/binnguci/todo-app/internal/controllers"
	"github.com/binnguci/todo-app/internal/repositories/user"
	user2 "github.com/binnguci/todo-app/internal/services/user"
	"gorm.io/gorm"
)

// Injectors from user.wire.go:

func InitUserRouterHandle(DB *gorm.DB) (*controllers.UserController, error) {
	iUserRepository := user.NewUserRepositoryImpl(DB)
	iUserService := user2.NewUserServiceImpl(iUserRepository)
	userController := controllers.NewUserController(iUserService)
	return userController, nil
}
