// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameAddress = "address"

// Address mapped from table <address>
type Address struct {
	gorm.Model
	ID          int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AddressLine string         `gorm:"column:address_line" json:"address_line"`
	Ward        string         `gorm:"column:ward" json:"ward"`
	District    string         `gorm:"column:district" json:"district"`
	Province    string         `gorm:"column:province" json:"province"`
	Country     string         `gorm:"column:country" json:"country"`
	IsDefault   bool           `gorm:"column:is_default" json:"is_default"`
	UserID      int64          `gorm:"column:user_id;not null" json:"user_id"`
}

func (*Address) TableName() string {
	return TableNameAddress
}
