// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID      int64          `gorm:"column:user_id;not null" json:"user_id"`
	TotalAmount float64        `gorm:"column:total_amount;not null" json:"total_amount"`
	Status      string         `gorm:"column:status;not null;default:Chờ xác nhận" json:"status"`
	Payment     string         `gorm:"column:payment;not null" json:"payment"`
	AddressID   int32          `gorm:"column:address_id;not null" json:"address_id"`
	CreatedAt   time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
