// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePromotion = "promotions"

// Promotion mapped from table <promotions>
type Promotion struct {
	ID                int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Code              string         `gorm:"column:code;not null" json:"code"`
	Description       string         `gorm:"column:description" json:"description"`
	DiscountPercent   float64        `gorm:"column:discount_percent" json:"discount_percent"`
	MaxDiscountAmount float64        `gorm:"column:max_discount_amount" json:"max_discount_amount"`
	StartDate         time.Time      `gorm:"column:start_date;not null" json:"start_date"`
	EndDate           time.Time      `gorm:"column:end_date;not null" json:"end_date"`
	UsageLimit        int32          `gorm:"column:usage_limit" json:"usage_limit"`
	IsActive          bool           `gorm:"column:is_active;default:1" json:"is_active"`
	CreatedAt         time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Promotion's table name
func (*Promotion) TableName() string {
	return TableNamePromotion
}
