// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePromotionOrder = "promotion_orders"

// PromotionOrder mapped from table <promotion_orders>
type PromotionOrder struct {
	ID          int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PromotionID int32 `gorm:"column:promotion_id;not null" json:"promotion_id"`
	OrderID     int64 `gorm:"column:order_id;not null" json:"order_id"`
}

// TableName PromotionOrder's table name
func (*PromotionOrder) TableName() string {
	return TableNamePromotionOrder
}
